In [10]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset.shape

(399, 25)

In [4]:
dataset = pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3,0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2,0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1,0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1,0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0,0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0,0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0,2,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3,0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0,0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0,0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [5]:
dataset.shape

(399, 28)

In [6]:
I = dataset [['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
D = dataset [['classification_yes']]

In [7]:
I.shape

(399, 27)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(I,D,test_size=1/3,random_state=0)

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier

grid_param = {'criterion' : ['gini', 'entropy', 'log_loss'],'splitter' :['best', 'random'],
              'max_features' : ['sqrt', 'log2', None]}

grid = GridSearchCV(DecisionTreeClassifier(), grid_param,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
30 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 942, in fit
    X_idx_sorted=X_idx_sorted,
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 352, in fit
    criterion = CRITERIA_CLF[self.criterion](
KeyError: 'log_loss'

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:972: UserWarning: One or more of the test scores are non-finite: [0.96227093 0.98506569 0.94024328 0.96981913 0.95444172 0.96267218
 0.93206597 0.95147573 0.95102634 0.96235105 0.93971783 0.96612431
        nan        nan        nan        nan        nan        nan]
  category=UserWarning,

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['sqrt', 'log2', None],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [20]:
y_pred = grid.predict(x_test)

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [22]:
from sklearn.metrics import classification_report
class_report = classification_report(y_test,y_pred)

In [23]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test,y_pred,average='weighted')

In [24]:
re = grid.cv_results_
print ("Best param {} and best score {}".format(grid.best_params_,grid.best_score_))

Best param {'criterion': 'gini', 'max_features': 'sqrt', 'splitter': 'random'} and best score 0.9850656883940017

In [25]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.9939024390243902

In [26]:
cm

array([[51,  0],
       [ 1, 81]], dtype=int64)

In [27]:
print(class_report)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133

In [24]:
x_test.shape

(133, 27)

In [28]:
table = pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009373,0.007653,0.003124,0.006249,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.981569,0.943041,0.943651,0.943093,1.000000,0.962271,0.024001,6
1,0.003124,0.006248,0.009373,0.007653,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.963284,0.981014,1.000000,1.000000,0.981031,0.985066,0.013807,1
2,0.006248,0.007653,0.006249,0.007653,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.908501,0.943041,0.925146,0.962264,0.962264,0.940243,0.021039,10
3,0.006249,0.007653,0.000000,0.000000,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.943041,0.962573,0.962264,0.981217,0.969819,0.019326,2
4,0.009373,0.007653,0.006249,0.007653,gini,None,best,"{'criterion': 'gini', 'max_features': None, 's...",0.962963,0.961755,0.962573,0.903887,0.981031,0.954442,0.026287,7
5,0.000000,0.000000,0.009371,0.007652,gini,None,random,"{'criterion': 'gini', 'max_features': None, 's...",0.963284,0.962264,0.981217,0.962573,0.944023,0.962672,0.011766,4
6,0.003124,0.006248,0.003124,0.006249,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.908501,0.883278,0.944023,0.962264,0.962264,0.932066,0.031313,12
7,0.006249,0.007653,0.000000,0.000000,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.945100,0.962264,0.981217,0.925146,0.943651,0.951476,0.018953,8
8,0.006249,0.007653,0.003124,0.006249,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.981569,0.923510,0.925524,0.962264,0.962264,0.951026,0.022773,9
9,0.006249,0.007654,0.000000,0.000000,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.961755,0.906705,0.962264,0.981031,0.962351,0.031187,5
10,0.006249,0.007653,0.003124,0.006248,entropy,None,best,"{'criterion': 'entropy', 'max_features': None,...",0.908877,0.942166,0.944023,0.922492,0.981031,0.939718,0.024410,11
11,0.009372,0.007652,0.003124,0.006249,entropy,None,random,"{'criterion': 'entropy', 'max_features': None,...",1.000000,0.943041,0.981217,0.925146,0.981217,0.966124,0.027623,3
12,0.003124,0.006249,0.000000,0.000000,log_loss,sqrt,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.003124,0.006249,0.000000,0.000000,log_loss,sqrt,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
14,0.000000,0.000000,0.000000,0.000000,log_loss,log2,best,"{'criterion': 'log_loss', 'max_features': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
15,0.006249,0.007653,0.000000,0.000000,log_loss,log2,random,"{'criterion': 'log_loss', 'max_features': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,16
16,0.003124,0.006248,0.000000,0.000000,log_loss,None,best,"{'criterion': 'log_loss', 'max_features': None...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
17,0.003124,0.006249,0.000000,0.000000,log_loss,None,random,"{'criterion': 'log_loss', 'max_features': None...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,18

In [83]:
age = float(input("Enter age of patient:"))
bp = float(input("Enter bp of patient:"))
al = float(input("Enter al of patient:"))
su = float(input("Enter su of patient:"))
bgr = float(input("Enter bgr of patient:"))
bu  = float(input("Enter bu of patient:"))
sc =  float(input("Enter sc of patient:"))
sod =  float(input("Enter sod of patient:"))
pot =  float(input("Enter pot of patient:"))
hrmo =  float(input("Enter hrmo of patient:"))
pcv =  float(input("Enter pcv of patient:"))
wc =  float(input("Enter wc of patient:"))
rc =  float(input("Enter rc of patient:"))
sg_b =  float(input("Enter sg b of patient o or 1:"))
sg_c = float(input("Enter sg c of patient o or 1:"))
sg_d = float(input("Enter sg d of patient o or 1:"))
sg_e = float(input("Enter sg e of patient o or 1:"))
rbc =  float(input("Enter rbc of patient o or 1:"))
pc=  float(input("Enter pc of patient o or 1:"))
pcc =  float(input("Enter pcc of patient o or 1:"))
ba =  float(input("Enter ba of patient o or 1:"))
htn =  float(input("Enter htn of patient o or 1:"))
dm =  float(input("Enter dm of patient o or 1:"))
cad =  float(input("Enter cad of patient o or 1:"))
appet =  float(input("Enter appet of patient o or 1:"))
pe =  float(input("Enter pe of patient o or 1:"))
ane =  float(input("Enter ane of patient o or 1:"))

result = grid.predict([[age, bp, al, su, bgr, bu, sc, sod, pot, hrmo, pcv,wc, rc, sg_b,sg_c,sg_d,sg_e,rbc, pc,pcc,ba,htn,dm,cad,appet,pe,ane]])
print(result)

Enter age of patient:17
Enter bp of patient:60
Enter al of patient:0
Enter su of patient:0
Enter bgr of patient:114
Enter bu of patient:50
Enter sc of patient:1
Enter sod of patient:135
Enter pot of patient:4.9
Enter hrmo of patient:14.2
Enter pcv of patient:51
Enter wc of patient:7200
Enter rc of patient:5.9
Enter sg b of patient o or 1:1
Enter sg c of patient o or 1:0
Enter sg d of patient o or 1:0
Enter sg e of patient o or 1:0
Enter rbc of patient o or 1:1
Enter pc of patient o or 1:1
Enter pcc of patient o or 1:1
Enter ba of patient o or 1:1
Enter htn of patient o or 1:1
Enter dm of patient o or 1:1
Enter cad of patient o or 1:1
Enter appet of patient o or 1:0
Enter pe of patient o or 1:0
Enter ane of patient o or 1:0
[1]

C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\base.py:442: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"

In [84]:
if result == 1:
    print("Based on inputs the patient may affect in Chronic Kindney Disease ")
else:
    print("Based on inputs the patient may NOT affect in Chronic Kindney Disease ")

Based on inputs the patient may affect in Chronic Kindney Disease