In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("CKD.csv")
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
dataset.shape

(399, 25)

In [4]:
dataset = pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3,0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2,0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1,0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1,0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0,0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0,0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0,2,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3,0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0,0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0,0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [5]:
dataset.shape

(399, 28)

In [6]:
I = dataset [['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
D = dataset [['classification_yes']]

In [7]:
I.shape

(399, 27)

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(I,D,test_size=1/3,random_state=0)

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

grid_param = {'penalty' : ['l1', 'l2', 'elasticnet', None],
              'solver' : ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'],
              'multi_class' : ['auto', 'ovr', 'multinomial']}

grid = GridSearchCV(LogisticRegression(), grid_param,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 72 candidates, totalling 360 fits

C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
265 fits failed out of a total of 360.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: Solver newton-cg supports only 'l2' or 'none' penalties, got l1 penalty.

--------------------------------------------------------------------------------
60 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 436, in _check_solver
    % (all_solvers, solver)
ValueError: Logistic Regression supports only solvers in ['liblinear', 'newton-cg', 'lbfgs', 'sag', 'saga'], got newton-cholesky.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: Solver sag supports only 'l2' or 'none' penalties, got l1 penalty.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 459, in _check_solver
    solver
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: Solver newton-cg supports only 'l2' or 'none' penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 449, in _check_solver
    % (solver, penalty)
ValueError: Solver sag supports only 'l2' or 'none' penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1473, in fit
    % self.l1_ratio
ValueError: l1_ratio must be between 0 and 1; got (l1_ratio=None)

--------------------------------------------------------------------------------
75 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 443, in _check_solver
    % (all_penalties, penalty)
ValueError: Logistic Regression supports only penalties in ['l1', 'l2', 'elasticnet', 'none'], got None.

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1519, in fit
    multi_class = _check_multi_class(self.multi_class, solver, len(self.classes_))
  File "C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 483, in _check_multi_class
    raise ValueError("Solver %s does not support a multinomial backend." % solver)
ValueError: Solver liblinear does not support a multinomial backend.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:972: UserWarning: One or more of the test scores are non-finite: [       nan 0.96985758        nan        nan        nan 0.48429303
 0.90609528 0.97748402 0.97360259        nan 0.48429303 0.48429303
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan 0.96985758        nan        nan        nan 0.48429303
 0.90609528 0.97748402 0.97360259        nan 0.48429303 0.48429303
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan 0.48429303
 0.91745669        nan 0.98121283        nan 0.48429303 0.48429303
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan]
  category=UserWarning,
C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\utils\validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:212: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  ConvergenceWarning,

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'multi_class': ['auto', 'ovr', 'multinomial'],
                         'penalty': ['l1', 'l2', 'elasticnet', None],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='f1_weighted', verbose=3)

In [10]:
y_pred = grid.predict(x_test)

In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [12]:
from sklearn.metrics import classification_report
class_report = classification_report(y_test,y_pred)

In [13]:
from sklearn.metrics import f1_score
f1 = f1_score(y_test,y_pred,average='weighted')

In [14]:
re = grid.cv_results_
print ("Best param {} and best score {}".format(grid.best_params_,grid.best_score_))

Best param {'multi_class': 'multinomial', 'penalty': 'l2', 'solver': 'newton-cg'} and best score 0.9812128263915746

In [15]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

1.0

In [16]:
cm

array([[51,  0],
       [ 0, 82]], dtype=int64)

In [17]:
print(class_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        51
           1       1.00      1.00      1.00        82

    accuracy                           1.00       133
   macro avg       1.00      1.00      1.00       133
weighted avg       1.00      1.00      1.00       133

In [18]:
x_test.shape

(133, 27)

In [19]:
table = pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_multi_class,param_penalty,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.002091,0.002272,0.000000,0.000000,auto,l1,lbfgs,"{'multi_class': 'auto', 'penalty': 'l1', 'solv...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,43
1,0.031081,0.007093,0.009735,0.004627,auto,l1,liblinear,"{'multi_class': 'auto', 'penalty': 'l1', 'solv...",0.981378,0.943041,0.981217,0.943651,1.0,0.969858,0.022699,6
2,0.001782,0.001459,0.000000,0.000000,auto,l1,newton-cg,"{'multi_class': 'auto', 'penalty': 'l1', 'solv...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,45
3,0.001916,0.001306,0.000000,0.000000,auto,l1,newton-cholesky,"{'multi_class': 'auto', 'penalty': 'l1', 'solv...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,46
4,0.002700,0.002086,0.000000,0.000000,auto,l1,sag,"{'multi_class': 'auto', 'penalty': 'l1', 'solv...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,0.003172,0.004899,0.000000,0.000000,multinomial,None,liblinear,"{'multi_class': 'multinomial', 'penalty': None...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,38
68,0.002771,0.004568,0.000000,0.000000,multinomial,None,newton-cg,"{'multi_class': 'multinomial', 'penalty': None...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,39
69,0.001284,0.001574,0.000000,0.000000,multinomial,None,newton-cholesky,"{'multi_class': 'multinomial', 'penalty': None...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,40
70,0.003082,0.003539,0.000000,0.000000,multinomial,None,sag,"{'multi_class': 'multinomial', 'penalty': None...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,66
71,0.001714,0.001079,0.000000,0.000000,multinomial,None,saga,"{'multi_class': 'multinomial', 'penalty': None...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,72

In [20]:
age = float(input("Enter age of patient:"))
bp = float(input("Enter bp of patient:"))
al = float(input("Enter al of patient:"))
su = float(input("Enter su of patient:"))
bgr = float(input("Enter bgr of patient:"))
bu  = float(input("Enter bu of patient:"))
sc =  float(input("Enter sc of patient:"))
sod =  float(input("Enter sod of patient:"))
pot =  float(input("Enter pot of patient:"))
hrmo =  float(input("Enter hrmo of patient:"))
pcv =  float(input("Enter pcv of patient:"))
wc =  float(input("Enter wc of patient:"))
rc =  float(input("Enter rc of patient:"))
sg_b =  float(input("Enter sg b of patient o or 1:"))
sg_c = float(input("Enter sg c of patient o or 1:"))
sg_d = float(input("Enter sg d of patient o or 1:"))
sg_e = float(input("Enter sg e of patient o or 1:"))
rbc =  float(input("Enter rbc of patient o or 1:"))
pc=  float(input("Enter pc of patient o or 1:"))
pcc =  float(input("Enter pcc of patient o or 1:"))
ba =  float(input("Enter ba of patient o or 1:"))
htn =  float(input("Enter htn of patient o or 1:"))
dm =  float(input("Enter dm of patient o or 1:"))
cad =  float(input("Enter cad of patient o or 1:"))
appet =  float(input("Enter appet of patient o or 1:"))
pe =  float(input("Enter pe of patient o or 1:"))
ane =  float(input("Enter ane of patient o or 1:"))

result = grid.predict([[age, bp, al, su, bgr, bu, sc, sod, pot, hrmo, pcv,wc, rc, sg_b,sg_c,sg_d,sg_e,rbc, pc,pcc,ba,htn,dm,cad,appet,pe,ane]])
print(result)

Enter age of patient:4
Enter bp of patient:12
Enter al of patient:0
Enter su of patient:0
Enter bgr of patient:1
Enter bu of patient:0
Enter sc of patient:0
Enter sod of patient:0
Enter pot of patient:0
Enter hrmo of patient:0
Enter pcv of patient:0
Enter wc of patient:0
Enter rc of patient:0
Enter sg b of patient o or 1:0
Enter sg c of patient o or 1:0
Enter sg d of patient o or 1:0
Enter sg e of patient o or 1:0
Enter rbc of patient o or 1:0
Enter pc of patient o or 1:0
Enter pcc of patient o or 1:0
Enter ba of patient o or 1:0
Enter htn of patient o or 1:0
Enter dm of patient o or 1:0
Enter cad of patient o or 1:0
Enter appet of patient o or 1:0
Enter pe of patient o or 1:0
Enter ane of patient o or 1:0
[1]

C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\base.py:442: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"

In [22]:
if result == 1:
    print("Based on inputs the patient may affect in Chronic Kindney Disease ")
else:
    print("Based on inputs the patient may NOT affect in Chronic Kindney Disease ")

Based on inputs the patient may affect in Chronic Kindney Disease

In [23]:
import pickle
pickle.dump(grid,open("final_LR_classification_model.sav",'wb'))

In [27]:
final= pickle.load(open("final_LR_classification_model.sav",'rb'))
final_result=final.predict([[1,2,3,1,0,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0]])
final_result

C:\Users\YAS\Anaconda3\lib\site-packages\sklearn\base.py:442: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"

array([1], dtype=uint8)